apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgres
  namespace: flux-system
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: my-postgres-app

  # Persistent storage configuration
  storage:
    storageClass: standard
    size: 1Gi
